import { prisma } from "@/app/lib/prisma/prisma";
import bcrypt from "bcrypt";
import crypto from "crypto";

// Total workspace seats including the Admin
export const PLAN_TEAM_LIMITS: Record<string, number> = {
  STARTER: 1, // Admin only (0 Managers)
  PROFESSIONAL: 5, // 1 Admin + up to 4 Managers
  ENTERPRISE: 999999, // Unlimited
};

// Manager seats allowed per subscription tier
export const PLAN_MANAGER_LIMITS: Record<string, number> = {
  STARTER: 0,
  PROFESSIONAL: 4,
  ENTERPRISE: 999999,
};

export interface TeamQuotaCheckResult {
  allowed: boolean;
  currentUsersCount: number;
  maxLimit: number;
  planSelected: string;
  assignedRole: "ADMIN" | "USER" | "MANAGER";
  message?: string;
}

export interface EmailUniquenessResult {
  isUnique: boolean;
  user?: {
    id: string;
    email: string;
    resetToken: string | null;
    resetTokenExpiry: Date | null;
  };
  hasActiveOtp: boolean;
}

/**
 * Worker check to ensure email addresses are strictly unique across all users.
 */
export async function checkEmailUniqueness(email: string): Promise<EmailUniquenessResult> {
  const trimmedEmail = email.trim().toLowerCase();

  const user = await prisma.user.findFirst({
    where: {
      email: { equals: trimmedEmail, mode: "insensitive" },
    },
    select: {
      id: true,
      email: true,
      resetToken: true,
      resetTokenExpiry: true,
    },
  });

  if (!user) {
    return { isUnique: true, hasActiveOtp: false };
  }

  const hasActiveOtp = Boolean(
    user.resetToken &&
      user.resetTokenExpiry &&
      new Date() < new Date(user.resetTokenExpiry)
  );

  return {
    isUnique: false,
    user,
    hasActiveOtp,
  };
}

/**
 * Platform Single-Atelier Policy:
 * Only ONE atelier ADMIN may register on the platform.
 * Once an ADMIN exists, all further public registrations are closed.
 * Staff members must join via an invite link generated by the active administrator.
 */
export async function checkAdminRegistrationEligibility(): Promise<{
  allowed: boolean;
  message?: string;
}> {
  const existingAdmin = await prisma.user.findFirst({
    where: { role: "ADMIN" },
    select: { id: true, companyName: true },
  });

  if (existingAdmin) {
    return {
      allowed: false,
      message:
        "Platform registration is closed. An administrator is already registered for this atelier. Staff members must join via an invite link issued by the administrator.",
    };
  }

  return { allowed: true };
}

/**
 * Retrieves the current team capacity, manager seats used, and plan details for an Admin.
 */
export async function getAdminTeamStats(adminId: string) {
  const admin = await prisma.user.findUnique({
    where: { id: adminId },
    select: {
      id: true,
      companyName: true,
      email: true,
      planSelected: true,
      paymentVerified: true,
      role: true,
    },
  });

  if (!admin) {
    throw new Error("Admin workspace not found.");
  }

  const currentManagersCount = await prisma.user.count({
    where: {
      role: "MANAGER",
      adminId: admin.id,
    },
  });

  const plan = admin.planSelected || "STARTER";
  const maxManagersAllowed = PLAN_MANAGER_LIMITS[plan] ?? 0;
  const totalSeats = PLAN_TEAM_LIMITS[plan] ?? 1;
  const currentSeatsUsed = 1 + currentManagersCount;
  const canAddManager = currentManagersCount < maxManagersAllowed;

  return {
    admin,
    planSelected: plan,
    currentManagersCount,
    maxManagersAllowed,
    totalSeats,
    currentSeatsUsed,
    canAddManager,
  };
}

/**
 * Creates a secure, single-use invite token for adding a MANAGER to the Admin's team.
 */
export async function createManagerInvite(adminId: string) {
  const stats = await getAdminTeamStats(adminId);
  if (!stats.canAddManager) {
    throw new Error(
      `Team seat capacity reached (${stats.currentManagersCount}/${stats.maxManagersAllowed} managers) for the ${stats.planSelected} plan. Upgrade your plan to invite more managers.`
    );
  }

  const token = crypto.randomBytes(32).toString("hex");
  const expiresAt = new Date();
  expiresAt.setDate(expiresAt.getDate() + 7); // 7-day token expiration

  const invite = await prisma.invite.create({
    data: {
      token,
      adminId: stats.admin.id,
      expiresAt,
      used: false,
    },
    include: {
      admin: {
        select: {
          id: true,
          companyName: true,
        },
      },
    },
  });

  return invite;
}

/**
 * Validates whether an invitation token is active, unused, and within capacity.
 */
export async function validateInviteToken(token: string) {
  if (!token || typeof token !== "string") {
    return { valid: false, error: "Invite token is required." };
  }

  const invite = await prisma.invite.findUnique({
    where: { token },
    include: {
      admin: {
        select: {
          id: true,
          companyName: true,
          email: true,
          planSelected: true,
        },
      },
    },
  });

  if (!invite) {
    return { valid: false, error: "Invalid invitation link." };
  }

  if (invite.used) {
    return { valid: false, error: "This invitation link has already been used." };
  }

  if (new Date() > new Date(invite.expiresAt)) {
    return { valid: false, error: "This invitation link has expired. Please request a new invite." };
  }

  const stats = await getAdminTeamStats(invite.adminId);
  if (!stats.canAddManager) {
    return {
      valid: false,
      error: `Workspace has reached maximum manager capacity (${stats.currentManagersCount}/${stats.maxManagersAllowed}). The administrator must upgrade their subscription.`,
    };
  }

  return {
    valid: true,
    invite,
    admin: invite.admin,
    companyName: invite.admin.companyName,
  };
}

/**
 * Atomically consumes an invite token and registers a new MANAGER attached to the Admin.
 */
export async function joinManagerWithInvite({
  token,
  name,
  email,
  phone,
  password,
}: {
  token: string;
  name: string;
  email: string;
  phone: string;
  password: string;
}) {
  const validation = await validateInviteToken(token);
  if (!validation.valid || !validation.invite || !validation.admin) {
    throw new Error(validation.error || "Invalid invitation.");
  }

  const admin = validation.admin;
  const trimmedEmail = email.trim().toLowerCase();

  const emailCheck = await checkEmailUniqueness(trimmedEmail);
  if (!emailCheck.isUnique) {
    throw new Error("An account with this email address already exists. Please log in.");
  }

  const hashedPassword = await bcrypt.hash(password, 10);
  const authorizationKey = `CMS-MGR-${crypto.randomBytes(6).toString("hex").toUpperCase()}`;

  const result = await prisma.$transaction(async (tx) => {
    // Re-verify invite inside the transaction
    const currentInvite = await tx.invite.findUnique({
      where: { token },
    });

    if (!currentInvite || currentInvite.used || new Date() > new Date(currentInvite.expiresAt)) {
      throw new Error("Invitation is no longer valid.");
    }

    // Re-verify quota inside the transaction
    const currentCount = await tx.user.count({
      where: { role: "MANAGER", adminId: admin.id },
    });
    const maxAllowed = PLAN_MANAGER_LIMITS[admin.planSelected] ?? 0;
    if (currentCount >= maxAllowed) {
      throw new Error("Workspace manager seat capacity reached.");
    }

    // Mark invite as used
    await tx.invite.update({
      where: { id: currentInvite.id },
      data: { used: true },
    });

    // Create Manager user attached to the Admin
    const manager = await tx.user.create({
      data: {
        companyName: admin.companyName, // Inherits company brand
        email: trimmedEmail,
        phone: phone.trim(),
        password: hashedPassword,
        authorizationKey,
        role: "MANAGER",
        adminId: admin.id,
        paymentVerified: true, // Uses Admin's verified status
        planSelected: admin.planSelected,
        subscription_status: "ACTIVE",
        storageUsed: 0,
        storageLimit: 0, // Managed under Admin's storage pool
      },
      select: {
        id: true,
        companyName: true,
        email: true,
        phone: true,
        role: true,
        adminId: true,
        createdAt: true,
      },
    });

    return manager;
  });

  return result;
}

/**
 * Removes a MANAGER from the workspace (Admin only).
 */
export async function removeManager(adminId: string, managerId: string) {
  const manager = await prisma.user.findFirst({
    where: {
      id: managerId,
      adminId,
      role: "MANAGER",
    },
  });

  if (!manager) {
    throw new Error("Manager not found in your workspace.");
  }

  await prisma.user.delete({
    where: { id: managerId },
  });

  return { success: true, deletedManagerId: managerId };
}

/**
 * Backwards-compatibility wrapper for legacy checks.
 */
export async function checkTeamMemberLimitAndRole(): Promise<TeamQuotaCheckResult> {
  const adminEligibility = await checkAdminRegistrationEligibility();
  const totalUsersCount = await prisma.user.count();

  if (adminEligibility.allowed) {
    return {
      allowed: true,
      currentUsersCount: totalUsersCount,
      maxLimit: 1,
      planSelected: "STARTER",
      assignedRole: "ADMIN",
    };
  }

  return {
    allowed: false,
    currentUsersCount: totalUsersCount,
    maxLimit: 1,
    planSelected: "STARTER",
    assignedRole: "USER",
    message: adminEligibility.message,
  };
}
